accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views 
from . import views

app_name = 'accounts'

urlpatterns = [
    # Login URL
    path('login/', views.user_login, name='login'),

    # Registration URL
    path('register/', views.register, name='register'),
    path('verify-email/<uidb64>/<token>/', views.verify_email, name='verify_email'),  # URL for email verification

    # Account URL
    path('account/', views.account_view, name='account'),  # Account details view

    # Logout URL
    path('logout/', views.logout_view, name='logout'),
]

beatclique_project/urls.py
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from . import views as project_views
from django.contrib import admin

# Define URL patterns
urlpatterns = [
    # Admin URL
    path('admin/', admin.site.urls),

    # Home URL
    path('', project_views.home, name='home'),

    # Soundkits URL
    path('soundkits/', include('soundkit.urls')),  # Include URLs for soundkits app

    # Accounts URL with namespace
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),  # Include URLs for accounts app

    # Vendor URL
    path('vendor/', include('vendor.urls')),  # Include URLs for vendor app

    # Payments URL
    path('payments/', include('payments.urls')),  # Include URLs for payments app

    # Cart URL with namespace
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),  # Include URLs for cart app
]

handler404 = 'beatclique_project.views.handler404'  # Custom view for 404 error
handler500 = 'beatclique_project.views.handler500'  # Custom view for 500 error

# Serve static and media files during development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # URL pattern to add a sound kit to the cart
    path('add-to-cart/<int:soundkit_id>/', views.add_to_cart, name='add_to_cart'),
    
    # URL pattern to view the contents of the cart
    path('view/', views.view_cart, name='view_cart'),
    
    # URL pattern to update the cart contents
    path('update/', views.update_cart, name='update_cart'),
]

payments/urls.py
from django.urls import path
from . import views

app_name = 'payments'

urlpatterns = [
    path('create-checkout-session/', views.create_checkout_session, name='create_checkout_session'),
    path('success/', views.payment_success, name='payment_success'),
    path('cancel/', views.payment_cancelled, name='payment_cancelled'),
    path('order-history/', views.order_history, name='order_history'),
    path('download/<int:order_item_id>/', views.download_product_file, name='download_product_file'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    bio = models.TextField(blank=True)
    email_verified = models.BooleanField(default=False)

    groups = models.ManyToManyField(
        'auth.Group',
        verbose_name='groups',
        blank=True,
        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
        related_name="customuser_groups", 
        related_query_name="customuser", 
    )

    user_permissions = models.ManyToManyField(
        'auth.Permission',
        verbose_name='user permissions',
        blank=True,
        help_text='Specific permissions for this user.',
        related_name="customuser_permissions",  
        related_query_name="customuser",
    )

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.contrib.auth import get_user_model
from django.core.mail import send_mail
from django.urls import reverse
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
from django.template.loader import render_to_string

User = get_user_model()
token_generator = PasswordResetTokenGenerator()

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True, request=None):
        user = super().save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
            # Generate token and UID for email verification link
            token = token_generator.make_token(user)
            uid = urlsafe_base64_encode(force_bytes(user.pk))
            link = reverse('accounts:verify_email', kwargs={'uidb64': uid, 'token': token})
            full_link = f'http://{request.get_host()}{link}'
            
            # Render the email template with the user and verification link
            email_context = {
                'user': user,
                'verification_url': full_link,
            }
            email_body = render_to_string('accounts/verification_email.html', email_context)
            
            # Send verification email using the rendered template
            send_mail(
                'Verify your email address',
                email_body,
                'beatclique.project@gmail.com',
                [user.email],
                fail_silently=False,
                html_message=email_body,
            )
        return user

# Removed AccountUpdateForm to disable email update functionality for now - will add back in for future developments

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib import messages
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.utils.http import urlsafe_base64_decode
from django.utils.encoding import force_str
from .forms import CustomUserCreationForm
from payments.models import Order

User = get_user_model()
token_generator = PasswordResetTokenGenerator()

# View for registering new users
def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            # Pass request to form's save method for email verification
            form.save(request=request)
            messages.success(request, 'Registration successful. Please check your email to verify your account.')
            return redirect('accounts:login')
    else:
        form = CustomUserCreationForm()
    return render(request, 'accounts/register.html', {'form': form})

# View for user login
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            if user.is_superuser:  # Check if the user is a superuser
                login(request, user)
                messages.success(request, 'Login successful.')
                return redirect('home')
            elif not user.email_verified:
                messages.error(request, 'Please verify your email address to login.')
                return redirect('accounts:login')
            else:
                login(request, user)
                messages.success(request, 'Login successful.')
                return redirect('home')
        else:
            messages.error(request, 'Invalid username or password.')
    return render(request, 'accounts/login.html')

# View for viewing user account details
@login_required
def account_view(request):
    if request.method == 'POST':
        user = request.user
        email = request.POST.get('email', user.email)
        user.email = email
        user.save()
        messages.success(request, 'Account details updated successfully.')  # Notify user of successful update
    return render(request, 'accounts/account.html')


# View for logging out users
@login_required
def logout_view(request):
    logout(request)
    messages.success(request, 'You have been logged out.') # Notify user of successful logout
    return redirect('home')

# View for displaying order history
@login_required
def order_history(request):
    orders = Order.objects.filter(user=request.user)
    return render(request, 'accounts/order_history.html', {'orders': orders})

# Function for email verification
def verify_email(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and token_generator.check_token(user, token):
        user.email_verified = True
        user.save()
        messages.success(request, 'Your email has been verified. You can now login.')
        return redirect('accounts:login')
    else:
        messages.error(request, 'The verification link is invalid or has expired.')
        return redirect('register')

accounts/templates/accounts/account.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Account - BeatClique{% endblock %}

{% block content %}
<section class="bg-dark d-flex justify-content-center align-items-center min-vh-100">
    <div class="container">
        <div class="card bg-white">
            <div class="card-body">
                <!-- Badge for superuser -->
                {% if request.user.is_superuser %}
                <div class="text-center mb-3">
                    <div class="alert alert-warning fs-4" role="alert">
                        Superuser
                    </div>
                </div>
                <!-- Button to take superuser to dashboard -->
                <div class="text-center mb-3">
                    <a href="{% url 'home' %}" class="btn btn-primary btn-md" aria-label="Dashboard">Dashboard</a>
                </div>
                {% endif %}
                <!-- Common content for all users -->
                {% if not request.user.is_superuser %}
                <!-- Heading for the account -->
                <h2 class="text-center mb-4">Your Account <i class="fa-solid fa-user ms-2"></i></h2>
                <!-- Displaying username -->
                <div class="text-center mb-3">
                    <h3>Username:</h3>
                    <p>{{ request.user.username }}</p>
                </div>
                <!-- Removed form for updating email but may add back in at a later development -->
                <!-- Button to navigate to order history (only visible for non-superusers) -->
                <hr>
                <h3 class="text-center my-3">Purchase History</h3>
                <div class="text-center">
                    <a href="{% url 'payments:order_history' %}" class="btn btn-info" aria-label="View Order History">View Order History</a>
                </div>
                <!-- Go to Soundkits button -->
                <div class="text-end mt-3">
                    <a href="{% url 'soundkit_list' %}" class="btn btn-primary" aria-label="Go to Soundkits"><i class="fas fa-arrow-left me-2"></i> Go to Soundkits</a>
                </div>
                {% endif %}
                <!-- Logout button -->
                <div class="text-center mt-3">
                    <form action="{% url 'accounts:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger btn-md" aria-label="Logout">Logout</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Login - BeatClique{% endblock %}

{% block content %}
<!-- Background Section -->
<section class="bg-dark d-flex justify-content-center align-items-center min-vh-100">
    <div class="container">
        <div class="card bg-white">
            <div class="card-body row">
                <!-- Photo on the left -->
                    <div class="col-md-6 d-none d-md-block">
                        <div class="card" style="border-radius: 50%; overflow: hidden;">
                            <img src="https://beatclique-assets.s3.eu-west-2.amazonaws.com/images/register/register_logo.webp" class="card-img-top rounded-circle" alt="Register Logo">
                        </div>
                    </div>
                <!-- Login Form -->
                <div class="col-md-6 d-flex align-items-center justify-content-center">
                    <div class="card mb-3" style="width: 100%;">
                        <div class="card-body">
                            <h2 class="text-center mb-4">Login</h2>
                            <!-- Form for login -->
                            <form method="post">
                                {% csrf_token %}
                                <div class="mb-3">
                                    <label for="id_username" class="form-label">Username:</label>
                                    <input type="text" class="form-control" name="username" id="id_username" autocomplete="username" required>
                                </div>
                                <div class="mb-3">
                                    <label for="id_password" class="form-label">Password:</label>
                                    <input type="password" class="form-control" name="password" id="id_password" autocomplete="current-password" required>
                                </div>
                                <div class="mb-3 d-flex justify-content-center">
                                    <button type="submit" class="btn btn-primary">Login</button>
                                </div>
                                {% if messages %}
                                    {% for message in messages %}
                                        <div class="alert alert-{{ message.tags }}" role="alert">
                                            {{ message }}
                                        </div>
                                    {% endfor %}
                                {% endif %}
                            </form>
                            <!-- Navigation link to registration page for users without an account -->
                            <p class="mt-3 text-center">Don't have an account? <a href="{% url 'accounts:register' %}" class="btn btn-link">Register here</a></p>
                            <!-- Notice for account issues -->
                            <p class="text-center mt-4">
                                If you have any account issues, please contact <a href="mailto:beatclique.project@gmail.com">beatclique.project@gmail.com</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Register - BeatClique{% endblock %}

{% block content %}
<section class="bg-dark d-flex justify-content-center align-items-center min-vh-100">
    <div class="container">
        <div class="card bg-white">
            <div class="card-body row">
                <!-- Photo on the left -->
                    <div class="col-md-6 d-none d-md-block">
                        <div class="card" style="border-radius: 50%; overflow: hidden;">
                            <img src="https://beatclique-assets.s3.eu-west-2.amazonaws.com/images/register/register_logo.webp" class="card-img-top rounded-circle" alt="Register Logo">
                        </div>
                    </div>
                <!-- Register Form -->
                <div class="col-md-6 d-flex align-items-center justify-content-center">
                    <div class="card mb-3" style="width: 100%;">
                        <div class="card-body">
                            <h2 class="text-center mb-4">Register</h2>
                            <form method="post">
                                {% csrf_token %}
                                <!-- Username Field -->
                                <div class="mb-3">
                                    <label for="id_username" class="form-label">Username:</label>
                                    <input type="text" name="username" id="id_username" class="form-control" autocomplete="username" value="{{ form.username.value|default_if_none:'' }}">
                                </div>
                                <!-- Email Field -->
                                <div class="mb-3">
                                    <label for="id_email" class="form-label">Email:</label>
                                    <input type="email" name="email" id="id_email" class="form-control" autocomplete="email" value="{{ form.email.value|default_if_none:'' }}">
                                </div>
                                <!-- Password1 Field -->
                                <div class="mb-3">
                                    <label for="id_password1" class="form-label">Password:</label>
                                    <input type="password" name="password1" id="id_password1" class="form-control" autocomplete="new-password">
                                </div>
                                <!-- Password2 Field -->
                                <div class="mb-3">
                                    <label for="id_password2" class="form-label">Confirm Password:</label>
                                    <input type="password" name="password2" id="id_password2" class="form-control" autocomplete="new-password">
                                </div>
                                <!-- Submit Button -->
                                <div class="text-center">
                                    <button type="submit" class="btn btn-success">Register</button>
                                </div>
                                {% if form.errors %}
                                    <div class="alert alert-danger mt-3" role="alert">
                                        {% for field, errors in form.errors.items %}
                                            {% for error in errors %}
                                                <div>{{ field|capfirst }}: {{ error }}</div>
                                            {% endfor %}
                                        {% endfor %}
                                    </div>
                                {% endif %}
                            </form>
                            <p class="mt-3 text-center">Already have an account? <a href="{% url 'accounts:login' %}" class="btn btn-link">Login here</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

accounts/templates/accounts/verification_email.html
{% block content %}

<h1>Email Verification Required</h1>

<p>Thank you for registering with BeatClique! To complete your registration and verify your email address, please click the link below:</p>
<p><a href="{{ verification_url }}">Verify Email Address</a></p>
<p>If you did not sign up for a BeatClique account, please ignore this email.</p>

{% endblock %}