accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views 
from . import views

app_name = 'accounts'

urlpatterns = [
    # Login URL
    path('login/', views.user_login, name='login'),

    # Registration URL
    path('register/', views.register, name='register'),
    path('verify-email/<uidb64>/<token>/', views.verify_email, name='verify_email'),  # URL for email verification

    # Account URL
    path('account/', views.account_view, name='account'),  # Account details view

    # Logout URL
    path('logout/', views.logout_view, name='logout'),
]

beatclique_project/urls.py
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from . import views as project_views
from django.contrib import admin

# Define URL patterns
urlpatterns = [
    # Admin URL
    path('admin/', admin.site.urls),

    # Home URL
    path('', project_views.home, name='home'),

    # Soundkits URL
    path('soundkits/', include('soundkit.urls')),  # Include URLs for soundkits app

    # Accounts URL with namespace
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),  # Include URLs for accounts app

    # Vendor URL
    path('vendor/', include('vendor.urls')),  # Include URLs for vendor app

    # Payments URL
    path('payments/', include('payments.urls')),  # Include URLs for payments app

    # Cart URL with namespace
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),  # Include URLs for cart app
]

handler404 = 'beatclique_project.views.handler404'  # Custom view for 404 error
handler500 = 'beatclique_project.views.handler500'  # Custom view for 500 error

# Serve static and media files during development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # URL pattern to add a sound kit to the cart
    path('add-to-cart/<int:soundkit_id>/', views.add_to_cart, name='add_to_cart'),
    
    # URL pattern to view the contents of the cart
    path('view/', views.view_cart, name='view_cart'),
    
    # URL pattern to update the cart contents
    path('update/', views.update_cart, name='update_cart'),
]

payments/urls.py
from django.urls import path
from . import views

app_name = 'payments'

urlpatterns = [
    path('create-checkout-session/', views.create_checkout_session, name='create_checkout_session'),
    path('success/', views.payment_success, name='payment_success'),
    path('cancel/', views.payment_cancelled, name='payment_cancelled'),
    path('order-history/', views.order_history, name='order_history'),
    path('download/<int:order_item_id>/', views.download_product_file, name='download_product_file'),
]

payments/models.py
from django.db import models
from django.conf import settings
from soundkit.models import SoundKit

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='orders')
    items = models.ManyToManyField(SoundKit, through='OrderItem')
    total = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    paid = models.BooleanField(default=False)

    def __str__(self):
        return f"Order {self.id} by {self.user.username}"

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    soundkit = models.ForeignKey(SoundKit, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.soundkit.name} in Order {self.order.id}"

payments/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib import messages
import stripe
from cart.models import Cart, CartItem
from .models import Order, OrderItem
from soundkit.models import SoundKit
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.http import HttpResponse, Http404
from django.core.files.base import ContentFile
import os
import boto3
from botocore.exceptions import NoCredentialsError

# Set Stripe's API key
stripe.api_key = settings.STRIPE_SECRET_KEY

@login_required
def create_checkout_session(request):
    # Retrieve the current user's cart
    cart = Cart.objects.get(user=request.user)
    line_items = []

    # Create a line item for each soundkit in the cart
    for item in cart.items.all():
        line_item = {
            'price_data': {
                'currency': 'gbp',
                'product_data': {
                    'name': item.soundkit.name,
                },
                'unit_amount': int(item.soundkit.price * 100),  # Price in pence
            },
            'quantity': item.quantity,
        }
        line_items.append(line_item)

    # Create Stripe Checkout Session
    checkout_session = stripe.checkout.Session.create(
        payment_method_types=['card'],
        line_items=line_items,
        mode='payment',
        success_url=request.build_absolute_uri('/') + 'payments/success/',
        cancel_url=request.build_absolute_uri('/') + 'payments/cancel/',
    )

    # Redirect to Stripe Checkout
    return redirect(checkout_session.url, code=303)

@login_required
def payment_success(request):
    try:
        # Attempt to retrieve the user's cart
        user_cart = Cart.objects.get(user=request.user)
        
        # Proceed with order creation and cart deletion logic only if cart exists
        total_cost = sum([item.soundkit.price * item.quantity for item in user_cart.items.all()])
        order = Order.objects.create(user=request.user, total=total_cost, paid=True)
        for item in user_cart.items.all():
            OrderItem.objects.create(order=order, soundkit=item.soundkit, quantity=item.quantity)
        
        # Clear user's cart after successful payment
        user_cart.delete()

        # Prepare email content
        context = {
            'username': request.user.username,
            'order_id': order.id,
            'total_amount': total_cost,
        }
        email_html_message = render_to_string('payments/emails/purchase_confirmation.html', context)
        subject = 'Your BeatClique Purchase Confirmation'
        email_from = settings.EMAIL_HOST_USER
        recipient_list = [request.user.email, ]

        # Send email
        send_mail(subject, "", email_from, recipient_list, html_message=email_html_message)
        
    except Cart.DoesNotExist:
        # If the cart does not exist, log the issue or inform the user as needed
        messages.warning(request, "Your cart does not exist. If you have already completed your payment, please ignore this message.")
    
    # Render the payment success template regardless of cart existence
    return render(request, 'payments/payment_success.html')

@login_required
def payment_cancelled(request):
    # Render the payment cancelled template
    return render(request, 'payments/payment_cancelled.html')

@login_required
def order_history(request):
    # Retrieve payment-related order history for the current user
    orders = Order.objects.filter(user=request.user)
    return render(request, 'payments/order_history.html', {'orders': orders})

@login_required
def download_product_file(request, order_item_id):
    """
    Redirects the user to the AWS S3 URL to securely download the product file
    if they have purchased it.
    """
    # Retrieve the specific order item to ensure the user has purchased it
    order_item = get_object_or_404(OrderItem, id=order_item_id, order__user=request.user)
    
    # Ensure there's a file associated with the sound kit
    if not order_item.soundkit.zip_file:
        return HttpResponse("No file available for download.", status=404)
    
    # Generate the S3 URL
    s3_client = boto3.client('s3',
                             aws_access_key_id=settings.AWS_ACCESS_KEY_ID,
                             aws_secret_access_key=settings.AWS_SECRET_ACCESS_KEY,
                             region_name=settings.AWS_S3_REGION_NAME)

    try:
        file_url = s3_client.generate_presigned_url('get_object',
                                                    Params={'Bucket': settings.AWS_STORAGE_BUCKET_NAME,
                                                            'Key': str(order_item.soundkit.zip_file)})
    except NoCredentialsError:
        return HttpResponse("Could not generate the download link.", status=500)

    return redirect(file_url)

payments/templates/payments/empty_cart.html
{% extends 'base.html' %}

{% block content %}
<section class="bg-dark d-flex justify-content-center align-items-center min-vh-100">
    <div class="container">
        <div class="card bg-white d-flex align-items-center justify-content-center" style="min-height: 200px;">
            <div class="card-body text-center">
                <h2 class="mb-4">Your Cart is Empty</h2>
                <p>You don't have any items in your cart. Start adding some!</p>
                <a href="{% url 'soundkit_list' %}" class="btn btn-primary">Browse Sound Kits</a>
            </div>
        </div>
    </div>
</section>
{% endblock %}

payments/templates/payments/error.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h2>An Error Occurred</h2>
    <p>{{ message }}</p>
    <a href="{% url 'home' %}" class="btn btn-primary">Return to Home</a>
</div>
{% endblock %}

payments/templates/payments/order_history.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Order History - BeatClique{% endblock %}

{% block content %}
<!-- Flex Container for entire content section -->
<div class="d-flex flex-column bg-dark" style="min-height: 100vh;">
    <!-- Heading Section-->
    <div class="py-4">
        <div class="container text-center text-white">
            <h2 class="mb-0">Order History <i id="order-history-icon" class="fas fa-truck-fast" style="font-size: 1em;"></i></h2>
        </div>
    </div>

    <!-- Content Section -->
    <section class="flex-grow-1 pb-5">
        <div class="container">
            <!-- Button to return to account page -->
                <div class="text-end mb-3">
                    <a href="{% url 'accounts:account' %}" class="btn btn-primary me-2"><i class="fas fa-arrow-circle-left"></i> Return to Account</a>
                </div>
            <!-- Orders -->
            {% if orders %}
                {% for order in orders %}
                    <div class="card mb-4">
                        <div class="card-header bg-primary text-white">
                            <div class="row align-items-center">
                                <div class="col-md-3">
                                    <h5 class="mb-0">Order ID: {{ order.id }}</h5>
                                </div>
                                <div class="col-md-3">
                                    <h5 class="mb-0">Date: {{ order.created_at|date:"M d, Y H:i" }}</h5>
                                </div>
                                <div class="col-md-3">
                                    <h5 class="mb-0">Total: £{{ order.total }}</h5>
                                </div>
                                <div class="col-md-3">
                                    <h5 class="mb-0">Status: {% if order.paid %}<span class="badge bg-success">Paid</span>{% else %}<span class="badge bg-warning text-dark">Pending</span>{% endif %}</h5>
                                </div>
                            </div>
                        </div>
                        <div class="card-body bg-light">
                            <h6 class="card-title">Items Purchased:</h6>
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th scope="col">Item</th>
                                            <th scope="col">Quantity</th>
                                            <th scope="col">Price</th>
                                            <th scope="col">Download</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for item in order.orderitem_set.all %}
                                            <tr>
                                                <td>{{ item.soundkit.name }}</td>
                                                <td>{{ item.quantity }}</td>
                                                <td>£{{ item.soundkit.price }}</td>
                                                <td>
                                                    {% if order.paid %}
                                                        <!-- Link to download purchased product -->
                                                        <a href="{% url 'payments:download_product_file' item.id %}" class="btn btn-primary">Download</a>
                                                    {% endif %}
                                                </td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="text-center text-white">
                    <p>No orders found.</p>
                </div>
            {% endif %}
        </div>
    </section>
</div>
{% endblock %}

payments/templates/payments/payment_cancelled.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Payment Cancelled - BeatClique{% endblock %}

{% block content %}
<!-- Black Background Section -->
<section class="bg-dark d-flex justify-content-center align-items-center min-vh-100">
    <div class="container">
        <div class="card bg-white d-flex align-items-center justify-content-center" style="min-height: 200px;">
            <div class="card-body text-center">
                <h2 class="mb-4">Payment Cancelled</h2>
                <p>Your payment has been cancelled.</p>
                <a href="{% url 'home' %}" class="btn btn-primary mt-3">Return to Home</a>
            </div>
        </div>
    </div>
</section>
{% endblock %}

payments/templates/payments/payment_success.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Payment Successful - BeatClique{% endblock %}

{% block content %}
<!-- Black Background Section -->
<section class="bg-dark d-flex justify-content-center align-items-center min-vh-100">
    <div class="container">
        <div class="card bg-white d-flex align-items-center justify-content-center" style="min-height: 200px;">
            <div class="card-body text-center">
                <h2 class="mb-4">Payment Successful</h2>
                <p>Your payment has been successfully processed.</p>
                <!-- Button to "Return to SoundKits" -->
                <a href="{% url 'soundkit_list' %}" class="btn btn-primary mt-3 mr-2">Return to SoundKits</a>
                <!-- Text explaining file downloads -->
                <p class="mt-3">Your purchased files are available for download in your account.</p>
                <!-- Button to "View Your Account" -->
                <a href="{% url 'accounts:account' %}" class="btn btn-success mt-3">View Your Account</a>
            </div>
        </div>
    </div>
</section>
{% endblock %}